# Generated by Django 3.2.15 on 2022-09-05 21:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'max_length': 'Die Bezeichnung darf maximal 254 Zeichen lang sein.', 'required': 'Bitte vergebe für deine Korrekturmeldung eine Bezeichnung.'}, max_length=254, validators=[django.core.validators.MinLengthValidator(10, message='Die Bezeichnung muss mindestens 10 Zeichen lang sein')], verbose_name='Bezeichnung')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(blank=True, error_messages={'max_length': 'Der Dateiname darf maximal 254 Zeichen lang sein.'}, max_length=254, null=True, validators=[django.core.validators.MinLengthValidator(10, message='Der Dateiname muss mindestens 10 Zeichen lang sein.')], verbose_name='Dateiname')),
                ('file', models.FileField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='Datei')),
                ('course', models.CharField(error_messages={'max_length': 'Die IU Kursbezeichnung darf maximal 255 Zeichen lang sein.'}, max_length=255, verbose_name='IU Kursbezeichnung')),
                ('report_status', models.CharField(blank=True, choices=[('1', 'Erstellt'), ('2', 'Zugewiesen'), ('3', 'Abgelehnt'), ('4', 'In Bearbeitung'), ('5', 'Warten auf Rückmeldung'), ('6', 'Abgeschlossen'), ('7', 'Geprüft')], default='1', max_length=2, null=True, verbose_name='Status der Korrekturmeldung')),
                ('report_type', models.CharField(choices=[('1', 'Fehler'), ('2', 'Verbesserung'), ('3', 'Rechtschreibfehler')], default='2', max_length=2, null=True, verbose_name='Art der Korrekturmeldung')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('qm_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qm_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
