# Generated by Django 3.2.15 on 2022-08-16 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255, verbose_name='Dateiname')),
                ('file', models.FileField(upload_to='%Y/%m/%d', verbose_name='Datei')),
                ('course', models.CharField(max_length=255, verbose_name='IU Kursbezeichnung')),
                ('report_status', models.CharField(choices=[('1', 'Gemeldet'), ('2', 'Zugewiesen'), ('3', 'In Bearbeitung'), ('4', 'Bearbeitet'), ('5', 'Abgewiesen')], default='1', max_length=2, null=True, verbose_name='Status der Korrekturmeldung')),
                ('report_type', models.CharField(choices=[('1', 'Hinweis'), ('2', 'Warnung'), ('3', 'Error'), ('4', 'Fatal')], default='1', max_length=2, null=True, verbose_name='Art der Korrekturmeldung')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('qm_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qm_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
