# Generated by Django 3.2.15 on 2022-09-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_system', '0002_correctionreport_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionreport',
            name='document_type',
            field=models.CharField(choices=[('1', 'Skript'), ('2', 'Literaturliste'), ('3', 'Online Tests'), ('4', 'Kursevaluation'), ('5', 'Musterklausur'), ('6', 'Musterlösung'), ('7', 'Foliensätze für Präsenzstudium'), ('8', 'Podcast'), ('9', 'Präsentation'), ('10', 'Interaktive Lehrveranstaltung'), ('11', 'Tutorium'), ('12', 'Dokumente Tutorium'), ('13', 'Repetitorium'), ('14', 'Learning Sprint'), ('15', 'Workbook Aufgaben'), ('16', 'Bootcamp'), ('17', 'Shortcast'), ('18', 'Live-Tutorial'), ('19', 'Aufgabenstellung: Schriftliche Ausarbeitung'), ('20', 'Videogalerie'), ('21', 'Pre-Assessment'), ('22', 'Sonstige Dokumente')], default='1', max_length=255, verbose_name='Lehrmaterial'),
        ),
        migrations.AlterField(
            model_name='correctionreport',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Ablehnungs Grund'),
        ),
        migrations.AlterField(
            model_name='correctionreport',
            name='report_status',
            field=models.CharField(blank=True, choices=[('1', 'Erstellt'), ('2', 'Zugewiesen'), ('3', 'Abgelehnt'), ('4', 'In Bearbeitung'), ('5', 'Warten auf Rückmeldung'), ('6', 'Abgeschlossen'), ('7', 'Geprüft')], default='1', max_length=255, null=True, verbose_name='Status der Korrekturmeldung'),
        ),
        migrations.AlterField(
            model_name='correctionreport',
            name='report_type',
            field=models.CharField(choices=[('1', 'Fehler'), ('2', 'Verbesserung'), ('3', 'Rechtschreibfehler')], default='2', max_length=255, null=True, verbose_name='Art der Korrekturmeldung'),
        ),
    ]
